#!/bin/mksh
# Description: dwm session script.

# When we die, take everyone with us.
function die {
	kill $(jobs -p)
}
trap die EXIT SIGHUP SIGINT SIGQUIT SIGTERM

# Files to source.
files=(
	"${HOME}/.autostart"
)
for f in "${files[@]}"; do
	[[ -r "${f}" ]] && . "${f}"
done

# Restart dwm if binary has change.
csum=$(sha1sum $(which dwm))
new_csum=""
while true
do
	dwm
	new_csum=$(sha1sum $(which dwm))
	if [[ "${csum}" != "${new_csum}" ]]
	then
		csum=${new_csum}
	else
		exit 0
	fi
done
